filebeat:
  prospectors:
    -
      paths:
        - /var/log/*/*.log
      input_type: log
      document_type: container-syslog
    -
      paths: 
        - /tmp/log/BookingService/*.log
      input_type: log
      document_type: BookingService

output:
  logstash:
    hosts: ["10.43.116.179:5044"]
    
shipper:

logging:
  to_syslog: false
  to_files: false