filebeat:
  prospectors:
    -
      paths:
        - /var/log/*/*.log
      input_type: log
      document_type: container-syslog
    -
      paths: 
        - /tmp/log/SeatOverviewService/*.log
      input_type: log
      document_type: SeatOverviewService

output:
  logstash:
    hosts: ["10.43.116.179:5044"]

shipper:

logging:
  to_syslog: false
  to_files: false